### PR TITLE
MIT relicense

### PR DESCRIPTION
**Pull request by RednedEpic**
Re-licenses the project under the MIT license. Will need permission from all contributors before this can be merged.

~~@DoctorMacc~~ ✓
~~@rtm516~~ ✓
~~@endevrr~~ ✓
~~@AJ-Ferguson~~ ✓ 
~~@OnlyBMan~~ ✓
~~@LogicismDev~~ ✓

All contributors will need to agree with this license being put on the project. If you do, please state so below.

### CODE REVIEW

**Comment by DoctorMacc** [comment]
I agree.

**Comment by OnlyBMan** [comment]
I agree 😄

**Comment by AJ-Ferguson** [comment]
I agree

**Comment by LogicismDev** [comment]
I agree.

**Comment by rtm516** [comment]
I agree

**Comment by endevrr** [comment]
Agreed

**Review by lukeeey — APPROVED** [review]

**Comment by jasoryeh** [comment]
I agree 💯

**Comment by RednedEpic** [comment]
Thanks!

**Pull request merged**
