### PR TITLE
Add collision to mappings

### PR DESCRIPTION
**Pull request by Heath123**
This is something I _might_ use in my move fixes PR, just posting it here so people can review it or tell me whether I should do that or stick to classes.
Example before:
```json
  "minecraft:anvil[facing=north]": {
    "bedrock_identifier": "minecraft:anvil",
    "block_hardness": 5.0,
    "can_break_with_hand": false,
    "tool_type": "pickaxe",
    "bedrock_states": {
      "damage": "undamaged",
      "direction": 2
    }
  },
```
Example after:
```json
  "minecraft:anvil[facing=north]": {
    "bedrock_identifier": "minecraft:anvil",
    "block_hardness": 5.0,
    "collision_index": 164,
    "can_break_with_hand": false,
    "tool_type": "pickaxe",
    "bedrock_states": {
      "damage": "undamaged",
      "direction": 2
    }
  },
```
Index 164 points here in collision.json:
```json
  [
    [
      0.125,
      0.0,
      0.125,
      0.875,
      0.25,
      0.875
    ],
    [
      0.1875,
      0.625,
      0.0,
      0.8125,
      1.0,
      1.0
    ],
    [
      0.25,
      0.25,
      0.1875,
      0.75,
      0.3125,
      0.8125
    ],
    [
      0.375,
      0.3125,
      0.25,
      0.625,
      0.625,
      0.75
    ]
  ],
```
Visualisation in Blender:
anvil-collision-blender
(I gave it fancy colours for some reason)

### CODE REVIEW

**Comment by DoctorMacc** [comment]
OK, if we're able to get collisions from Minecraft itself I am in support of this.

However, this will probably lead to a lot of duplicate lines (for example, that collision will be replaced at least three times) - we should see if there's a way to store all collisions in a `collisions.json` file and the mappings just say `collision_type: anvil_north`.

**Comment by Heath123** [comment]
Hmm, I'll give that a go. I was planning to just do that at runtime though, but that would cut down on file size.

**Comment by DoctorMacc** [comment]
Might as well do it here since there's no limit on time when running the mappings generator.

**Comment by Heath123** [comment]
True

**Comment by Heath123** [comment]
@DoctorMacc Done, and I updated the PR description to match

**Comment by Heath123** [comment]
https://github.com/GeyserMC/mappings/pull/40

**Pull request merged**
